### ISSUE TITLE
"bratsubset.annotation.InvalidIdError: Invalid id:" thrown if a line starts with \t

### ISSUE THREAD

**Issue by aam1r** [vwoloszyn/diaa#1]
**How to reproduce**

1. Create a file called `test.json`
2. Add the following contents:

```json
{"id": 603, "text": "Thanks!\n\tMichael Scott", "annotations": [{"label": 9, "start_offset": 1, "end_offset": 20, "user": 11}, {"label": 9, "start_offset": 1, "end_offset": 20, "user": 9}], "meta": {}, "annotation_approver": null}
```

3. Run `python main.py -i test.json`

**What happens**

You will get an error:

```
bratsubset.annotation.InvalidIdError: Invalid id: 
```

**My analysis**

This seems to happen in `bratsubset` because a line starts with `\t`.

If you replace the `\t` with `\n` or with a single space, it seems to work fine.

**Comment by vwoloszyn** [comment]
Hi, thanks for letting me know. It's an issue of bratiaa library used for computing the f1 scores. However, I have solved it by replacing the "\t" with space. It must be working now ;)
